config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  get "/tracking", to: "pages#tracking" 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :tracking
end

app/models/tracking.rb
class Tracking < ApplicationRecord
    validates :tracking_code, uniqueness: { case_sensitive: false}

    has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

  def tracking
  
    @tracking = Tracking.new(tracking_code: params[:tracking_code])
    
    if @tracking.save
      set_histories(@tracking)
      flash[:alert] = "Rastreio Salvo"
    else
      @tracking = Tracking.find_by(tracking_code: params[:tracking_code])
      @tracking.histories.destroy_all
      set_histories(@tracking)
    end

    @trackings = Tracking.all
  end
    
  private

  def set_histories(tracking)
    agent = Mechanize.new
    page = agent.get "https://proxyapp.correios.com.br/v1/sro-rastro/#{tracking.tracking_code}"
    
    response = JSON.parse(page.body) #Analisar o JSON
    
    if response["objetos"].first["eventos"]
      response["objetos"].first["eventos"].each do |evento|
        History.create(description: evento["descricao"], icon: evento["urlIcone"], tracking: tracking,data: evento["dtHrCriado"])
      end
    
      flash[:alert] = "Rastreio já cadastrado no BD"
    else
      tracking.destroy
      flash[:alert]="Codigo de Rastreio Invalido"
      render :index
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteRastreio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<header>
    <nav>
        <h1>Rastrei Aqui</h1>
    </nav>
</header>

    <div class="conteiner">
        
        <div class="formRastreio">
        <h2>RASTREI AQUI</h2>
        <p>Rastreie seus Itens Aqui</p>
        
        <%= form_with url: tracking_url, method: :get  do |form| %>
            <%= form.text_field :tracking_code ,placeholder:"Digite o Código de Rastreio", size:"23", maxlength:"13",minlength:"13" %>
            <%= form.submit "Pesquisar"%>
        <% end %>

        </div>
    </div>


    <footer>
            © 2022 Copyright:
    </footer>

    <style>

        body
        {
            margin: 0px;
        }

        header
        {
            padding: 20px;
            background-color: rgb(25, 0, 255);
            text-align: center;
            color: white;
        }

        .conteiner
        {
            display: flex;
            justify-content: center;
            text-align: center;
            padding: 100px;
            margin: 100px 500px;
            background-color: rgb(152, 152, 152);
        }

        footer
        {
            background-color: #444444;
            position:absolute;
            bottom:0;
            height: 100px;
            width:100%;
            text-align: center;
            justify-content: center;
        }
        
    </style>

app/views/pages/tracking.html.erb
<header>
    <nav>
        <h1>Rastreios.com</h1>
    </nav>
</header>

<% @trackings.each do |tracking| %>
    <div>
        <table class="table table-dark">
    
            <h4><%= tracking.tracking_code%></h4>
            <hr>
            <tr>
                <th>Situação</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
            <% tracking.histories.each do |history|%>
                <tr>
                    <th><%= image_tag "https://proxyapp.correios.com.br#{history.icon}" %></td>
                    <th><%= history.description %></td>
                    <th><%= history.data %></td>
                </tr>

            <% end %>
        </table>
    <div>    
<%end%>



<footer>
    <p>@2022</p>
</footer>

<style>

    body
    {
        margin: 0px;
    }

    header
    {
        padding: 20px;
        background-color: rgb(25, 0, 255);
        text-align: center;
        color: white;
    }

    .conteiner
    {
        display: flex;
        justify-content: center;
        text-align: center;
        padding: 100px;
        margin: 50px 500px;
        background-color: rgb(152, 152, 152);
    }

    footer
    {
        background-color: #444444;
        position:absolute;
	    bottom:0;
        height: 100px;
	    width:100%;
        text-align: center;
    }
</style>